---
title: "Written Report"
author: "Lisa Eisler"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
```

## Data import 

```{r, message=FALSE, warning=FALSE}
nsqipspineCP_1617 = read_csv("./data/nsqipspineCP_1617.csv")
```

note: Where variable type and length disagree, we get error message. Coercion occurs and outcome is all numeric/all character for any given column with longest length.

## Data simplification and coding

```{r}
cp_spine_tidy = nsqipspineCP_1617 %>%
  mutate_if(is.numeric, ~replace(., . == -99, NA)) %>%
  mutate(
    age_years = age_days/365.25,
    height = height*2.54,
    weight = weight/2.2) %>%
  mutate(
    bmi = weight/((height/100)*(height/100)),
    asa_status = case_when(
      asaclas == "ASA 1 - No Disturb" ~ "1",
      asaclas == "ASA 2 - Mild Disturb" ~ "2",
      asaclas == "ASA 3 - Severe Disturb" ~ "3",
      asaclas == "ASA 4 - Life Threat" ~ "4",
      asaclas == "None assigned" ~ "NA"),
    home_discharge = case_when(
      dischdest == "Expired" ~ "FALSE",
      dischdest == "Facility Which was Home" ~ "TRUE",
      dischdest == "Home" ~ "TRUE",
      dischdest == "Rehab" ~ "FALSE",
      dischdest == "Separate Acute Care" ~ "FALSE",
      dischdest == "Skilled Care, Not Home" ~ "FALSE",
      dischdest == "Unknown" ~ "NA",
      dischdest == "Unskilled Facility Not Home" ~ "FALSE",
      dischdest == "NULL" ~ "NA"
    )) %>%
  select(pufyear_x:ped_spn_post_neurodeftype, age_years, sex, height, weight, bmi, ethnicity_hispanic, race, asa_status, transt, ventilat, asthma, hxcld, oxygen_sup, crf, impcogstat, seizure, nutr_support, hemodisorder, optime, tothlos, d_opto_dis, death30yn, supinfec, wndinfd, orgspcssi, dehis, oupneumo, pulembol, renainsf, urninfec, cszre, neurodef, cdarrest, othbleed, bleed_ml_tot, othcdiff, othsysep, unplannedreadmission1, reoperation, dischdest, home_discharge)
```

```{r}
cp_spine_tidy %>%
  group_by(reoperation) %>%
  summarize(n = n())
```

## Patient Demographics
```{r}
data_sex = cp_spine_tidy %>%
  group_by(reoperation) %>% 
  count(sex) %>% 
  pivot_wider(
    names_from = "reoperation",
    values_from = "n"
  ) %>% 
  janitor::clean_names() %>% 
  mutate(percent = (yes/(no + yes))*100)
```

```{r}
data_age = cp_spine_tidy %>%
  group_by(reoperation) %>% 
  summarize(mean_age = mean(age_years), sd = sd(age_years))

data_weight = cp_spine_tidy %>%
  group_by(reoperation) %>% 
  summarize(mean_weight = mean(weight, na.rm = TRUE), sd = sd(weight, na.rm = TRUE))
```

```{r}
cp_spine_tidy %>%
  group_by(reoperation) %>% 
  count(sex)

cp_spine_tidy %>%
  group_by(reoperation) %>% 
  count(race)

cp_spine_tidy %>%
  group_by(reoperation) %>% 
  count(ethnicity_hispanic)
```
 
